Repository trustlines-network/relay, pull requests merged in 2018-08, with the labels that each got.

#176 Revert "Update to python 3.6"
  Dockerfile
  README.md
  docs/RelayServer.md
  relay/api/tokens/resources.py
  relay/blockchain/currency_network_proxy.py
  relay/blockchain/proxy.py
  relay/ethindex_db.py
  relay/relay.py
  relay/streams.py
  relay/utils.py
  setup.py
Labels: Bug

#175 Add paymentrequest over pushnotification
  relay/api/messaging/resources.py
  relay/api/schemas.py
  relay/api/streams/rpc_methods.py
  relay/api/streams/transport.py
  relay/events.py
  relay/pushservice/client.py
  relay/pushservice/pushservice.py
  relay/relay.py
  relay/streams.py
  tests/unit/test_streams.py
Labels: type:feature

#180 Handle cases where part of address.json is missing
  relay/relay.py
Labels: type:feature

#181 Remove deprecated address field
  relay/api/schemas.py
Labels: type:feature

#184 fix docker-compose based setup
  docker/trustlines/README.md
  docker/trustlines/docker-compose.yml
Labels: type:documentation
